copyright: © MushroomLabs 2020

docs_dir: src
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences

nav:
  - Home: index.md
  - Tutorials:
      - Introduction: tutorials/index.md
      - A Quick Look at Hub20: tutorials/overview.md
      - Generate secrets for managed wallets: tutorials/wallet.md
      - Deploying Hub20: tutorials/deployment.md
      - Setup user accounts: tutorials/user_accounts.md
      - Funding wallets: tutorials/funding.md
      - Execute Raiden contracts: tutorials/raiden.md

  - HOWTOs:
      - Installation: howtos/installation.md
      - Custom authentication: howtos/authentication.md
      - Select tokens: howto/tokens.md
      - Deployment: howto/deployment.md
      - Setup Raiden: howto/raiden.md
      - Use HD Wallets: howto/hd_wallets.md
      - Customize Checkout20 Widget: howto/checkout20.md
      - Troubleshooting: howto/troubleshooting.md

  - Topic Guides:
      - Architecture: topics/architecture.md
      - Features: topics/features.md
      - Use Cases: topics/use_cases.md
      - Raiden: topics/raiden.md
      - Accounting: topics/accounting.md

  - Reference:
      - reference/index.md
      - Authentication: reference/authentication.md
      - Wallet Engines: reference/wallets.md
      - API: reference/api.md
      - CLI: reference/cli.md
      - Configuration: reference/configuration.md

  - HOWTOs:
      - Installation: howtos/installation.md
      - Custom authentication: howtos/authentication.md
      - Select tokens: howto/tokens.md
      - Deployment: howto/deployment.md
      - Setup Raiden: howto/raiden.md
      - Use HD Wallets: howto/hd_wallets.md
      - Customize Checkout20 Widget: howto/checkout20.md
      - Troubleshooting: howto/troubleshooting.md

  - User manual:
      - manual/index.md
      - Accounts:
          - manual/accounts/register.md
          - manual/accounts/profile.md
      - Wallet:
          - View Balances: manual/wallet/view.md
          - Receive Deposits: manual/wallet/add_funds.md
          - Send/Withdraw Funds: manual/wallet/withdraw.md
      - History: manual/history.md
      - Create Merchant Store: manual/merchant_stores.md

  - FAQ: faq.md

plugins:
  - search
  - render_swagger
  - macros:
      include_dir: snippets

repo_name: mushroomlabs/hub20
repo_url: https://github.com/mushroomlabs/hub20

site_url: https://docs.hub20.io
site_name: Hub20

theme:
  custom_dir: theme
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  language: en
  palette:
    primary: indigo
    accent: indigo
